// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
//A class for default firebase options
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDK_iiHLRlzSEucTCEMpd2P6fcENmgF8',
    appId: '1:660530278090:web:9a24d6cf060195a26a0e33',
    messagingSenderId: '660530278090',
    projectId: 'travela-d3bd4',
    authDomain: 'travela-d3bd4.firebaseapp.com',
    storageBucket: 'travela-d3bd4.appspot.com',
    measurementId: 'G-EM54F7PFYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQWViDRkWH9j0ocHGgl2O4-MWgdG23-0',
    appId: '1:660530278090:android:02f33ab32a54f0006a0e33',
    messagingSenderId: '660530278090',
    projectId: 'travela-d3bd4',
    storageBucket: 'travela-d3bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxIHkZzJU6M7-YGZL6vWEVQj7dnK_l5N8',
    appId: '1:660530278090:ios:b22ff7bbe29b5ce76a0e33',
    messagingSenderId: '660530278090',
    projectId: 'travela-d3bd4',
    storageBucket: 'travela-d3bd4.appspot.com',
    iosClientId: '660530278090-hckml9iqhmu073amk4nncvn1ds85a90h.apps.googleusercontent.com',
    iosBundleId: 'com.example.travela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxIHkZzJU6M7-YGZL6vWEVQj7dnK_l5N8',
    appId: '1:660530278090:ios:b22ff7bbe29b5ce76a0e33',
    messagingSenderId: '660530278090',
    projectId: 'travela-d3bd4',
    storageBucket: 'travela-d3bd4.appspot.com',
    iosClientId: '660530278090-hckml9iqhmu073amk4nncvn1ds85a90h.apps.googleusercontent.com',
    iosBundleId: 'com.example.travela',
  );
}
